name: Selenium UI Testing ðŸ§‘â€ðŸ’»ï¸

on:
  pull_request:
  workflow_dispatch:

jobs:
  serve_and_test_chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Use Node.js
        env:
          NODE: 16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            .veda/ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
  
      - name: Cache dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.workflow }}-${{ github.sha }}

      - name: Install
        run: |
          ./.veda/setup
          pip install selenium==4.11.2
      
      - name: Serve and Test Chrome
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID }}
          GOOGLE_TAG_AUTH: ${{ secrets.GOOGLE_TAG_AUTH }}
          GOOGLE_TAG_PREVIEW: ${{ secrets.GOOGLE_TAG_PREVIEW }}
          DASHBOARD_BASE_URL: http://localhost:9000
          OUTPUT_DIR: ${{ github.workspace }}/output
        run: |
          nohup yarn serve > serve.log 2>&1 &
          sleep 10
          cd tests
          python selenium_ui_test.py
        
      - name: Kill yarn serve
        run: pkill -f "yarn serve"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: ${{ github.workspace }}/output

  serve_and_test_firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Use Node.js
        env:
          NODE: 16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            .veda/ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
  
      - name: Cache dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.workflow }}-${{ github.sha }}

      - name: Install
        run: |
          ./.veda/setup
          pip install selenium==4.11.2
      
      - name: Serve and Test Firefox
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID }}
          GOOGLE_TAG_AUTH: ${{ secrets.GOOGLE_TAG_AUTH }}
          GOOGLE_TAG_PREVIEW: ${{ secrets.GOOGLE_TAG_PREVIEW }}
          DASHBOARD_BASE_URL: http://localhost:9000
          OUTPUT_DIR: ${{ github.workspace }}/output
        run: |
          nohup yarn serve > serve.log 2>&1 &
          sleep 10
          cd tests
          python selenium_ui_test_firefox.py
        
      - name: Kill yarn serve
        run: pkill -f "yarn serve"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: ${{ github.workspace }}/output

  serve_and_test_edge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Use Node.js
        env:
          NODE: 16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            .veda/ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
  
      - name: Cache dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.workflow }}-${{ github.sha }}

      - name: Install
        run: |
          ./.veda/setup
          pip install selenium==4.11.2
      
      - name: Serve and Test Edge
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID }}
          GOOGLE_TAG_AUTH: ${{ secrets.GOOGLE_TAG_AUTH }}
          GOOGLE_TAG_PREVIEW: ${{ secrets.GOOGLE_TAG_PREVIEW }}
          DASHBOARD_BASE_URL: http://localhost:9000
          OUTPUT_DIR: ${{ github.workspace }}/output
        run: |
          nohup yarn serve > serve.log 2>&1 &
          sleep 10
          cd tests
          python selenium_ui_test_edge.py
        
      - name: Kill yarn serve
        run: pkill -f "yarn serve"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: ${{ github.workspace }}/output